version: '3'
services:
  demo:
    image: lk168/hellojava:1.0.1
    ports:
      - 8080:8080
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 0.5G
      update_config:
        parallelism: 1
        delay: 30s
    healthcheck:
      test: ["CMD-SHELL", "curl -s -X GET http://127.0.0.1:8080/health | grep 'UP'"]
      interval: 3s
      timeout: 5s
      retries: 3
